-- MySQL Script generated by MySQL Workbench
-- Wed May 25 22:17:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_blog_pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_blog_pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_blog_pessoal` DEFAULT CHARACTER SET utf8 ;
USE `db_blog_pessoal` ;

-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`tb_marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`tb_marcas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`Usuário` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cadastro (nome, endereco, CNPJ)` VARCHAR(255) NULL,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`tab_vinhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`tab_vinhos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `regiao` VARCHAR(255) NOT NULL,
  `dados(nome, preco, tipo)` VARCHAR(255) NULL,
  `disponibilidade` VARCHAR(255) NULL,
  `tb_marcas_id` BIGINT NOT NULL,
  `Usuário_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tab_vinhos_tb_marcas_idx` (`tb_marcas_id` ASC) VISIBLE,
  INDEX `fk_tab_vinhos_Usuário1_idx` (`Usuário_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_vinhos_tb_marcas`
    FOREIGN KEY (`tb_marcas_id`)
    REFERENCES `db_blog_pessoal`.`tb_marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_vinhos_Usuário1`
    FOREIGN KEY (`Usuário_id`)
    REFERENCES `db_blog_pessoal`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
